name: coptic_reader
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0-265.0.dev

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  excel: ^2.0.4
  sqflite: ^2.3.0
  path: ^1.8.0
  path_provider: ^2.1.0 
  package_info_plus: ^4.0.0
  flutter_colorpicker: ^1.0.3
  flutter_phoenix: ^1.0.0
  intl: ^0.18.0
  mysql1: ^0.20.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/excel/Vespers.xlsx
    - assets/db/bible.sqlite
    - assets/logo.png
