class Values {
  static final Map<String, Map<String, String>> nameValues = {
    'en': {
      'app_name': 'China Coptic',
      'home_page': 'Home',
      'bible_page': 'Bible',
      'catalogue_page': 'Catalogue',
      'listen_page': 'Listen',
      'account_page': 'Mine',
      'cat_agpeya': 'Agpeya',
      'cat_psalmody': 'Psalmody',
      'cat_liturgies': 'Liturgies',
      'cat_melodies': 'Melodies',
      'cat_clergy': 'Clergy',
      'cat_readings': 'Readings',
      'cat_index': 'Index',
      'cat_special': 'Special',
      'read_vespers': 'Vespers',
      'read_matins': 'Matins',
      'read_Liturgy': 'Liturgy',
      'read_antiphonary': 'Antiphonary',
      'acc_login': 'Login',
      'acc_messages': 'Messages',
      'acc_favorite': 'Favorites',
      'acc_settings': 'Settings',
      'acc_aboutapp': 'About App',
      'acc_feedback': 'Feedback',
      'acc_contactus': 'Contact Us',
      'sett_fontsize': 'Font Size',
      'sett_fontstyle': 'Font Style',
      'sett_fontcolor': 'Font Color',
      'sett_defaultlang': 'Default Language',
      'sett_savesettings': 'Save Settings',
      'sett_choosecolor': 'Choose Color',
      'sett_appearance': 'Appearance',
      'sett_reading_settings': 'Reading Settings',
      'sett_language_settings': 'Language Settings',
      'sett_default_language': 'Default Language',
      'sett_display_language_1': 'Display Language 1',
      'sett_display_language_2': 'Display Language 2',
      'agpeya_first': '1st Hour',
      'agpeya_third': '3rd Hour',
      'agpeya_sixth': '6th Hour',
      'agpeya_nineth': '9th Hour',
      'agpeya_eleventh': '11th Hour',
      'agpeya_twelfth': '12th Hour',
      'agpeya_viel': 'Veil',
      'agpeya_midnight': 'Midnight',
      'agpeya_prayers': 'Prayers',
      'settings_saved_pop': 'Settings saved, please restart the App.',
      'reader_page_sections_header': 'Sections',
      'home_father_message': 'Message From Father',
      'home_read_bible': 'Read the Bible',
      'home_listen_to_sermon': 'Listen to Sermon',
      'home_readings': 'Readings',
      'home_agpeya': 'Agpeya',
      'home_todays_readings': 'Today\'s Readings',
      'sett_disp_lang1': 'Display Language 1',
      'sett_disp_lang2': 'Display Language 2',
      'bible_old_testament': 'Old Testament',
      'bible_new_testament': 'New Testament',
      'bible_chapters': 'Chapters',
      'bible_genesis': 'Genesis',
      'bible_exodus': 'Exodus',
      'bible_leviticus': 'Leviticus',
      'bible_numbers': 'Numbers',
      'bible_deuteronomy': 'Deuteronomy',
      'bible_joshua': 'Joshua',
      'bible_judges': 'Judges',
      'bible_ruth': 'Ruth',
      'bible_1_samuel': '1 Samuel',
      'bible_2_samuel': '2 Samuel',
      'bible_1_kings': '1 Kings',
      'bible_2_kings': '2 Kings',
      'bible_1_chronicles': '1 Chronicles',
      'bible_2_chronicles': '2 Chronicles',
      'bible_ezra': 'Ezra',
      'bible_nehemiah': 'Nehemiah',
      'bible_esther': 'Esther',
      'bible_job': 'Job',
      'bible_psalms': 'Psalms',
      'bible_proverbs': 'Proverbs',
      'bible_ecclesiastes': 'Ecclesiastes',
      'bible_song_of_songs': 'Song of Songs',
      'bible_isaiah': 'Isaiah',
      'bible_jeremiah': 'Jeremiah',
      'bible_lamentations': 'Lamentations',
      'bible_ezekiel': 'Ezekiel',
      'bible_daniel': 'Daniel',
      'bible_hosea': 'Hosea',
      'bible_joel': 'Joel',
      'bible_amos': 'Amos',
      'bible_obadiah': 'Obadiah',
      'bible_jonah': 'Jonah',
      'bible_micah': 'Micah',
      'bible_nahum': 'Nahum',
      'bible_habakkuk': 'Habakkuk',
      'bible_zephaniah': 'Zephaniah',
      'bible_haggai': 'Haggai',
      'bible_zechariah': 'Zechariah',
      'bible_malachi': 'Malachi',
      'bible_matthew': 'Matthew',
      'bible_mark': 'Mark',
      'bible_luke': 'Luke',
      'bible_john': 'John',
      'bible_acts': 'Acts',
      'bible_romans': 'Romans',
      'bible_1_corinthians': '1 Corinthians',
      'bible_2_corinthians': '2 Corinthians',
      'bible_galatians': 'Galatians',
      'bible_ephesians': 'Ephesians',
      'bible_philippians': 'Philippians',
      'bible_colossians': 'Colossians',
      'bible_1_thessalonians': '1 Thessalonians',
      'bible_2_thessalonians': '2 Thessalonians',
      'bible_1_timothy': '1 Timothy',
      'bible_2_timothy': '2 Timothy',
      'bible_titus': 'Titus',
      'bible_philemon': 'Philemon',
      'bible_hebrews': 'Hebrews',
      'bible_james': 'James',
      'bible_1_peter': '1 Peter',
      'bible_2_peter': '2 Peter',
      'bible_1_john': '1 John',
      'bible_2_john': '2 John',
      'bible_3_john': '3 John',
      'bible_jude': 'Jude',
      'bible_revelation': 'Revelation',
      'bible_tobit': 'Tobit',
      'bible_judith': 'Judith',
      'bible_wisdom': 'Wisdom of Solomon',
      'bible_sirach': 'Sirach',
      'bible_baruch': 'Baruch',
      'bible_1_maccabees': '1 Maccabees',
      'bible_2_maccabees': '2 Maccabees',
      'bible_prayer_of_manasseh': 'Prayer of Manasseh',
      'bible_search_hint': 'Search in Bible...',
      'bible_previous': 'Previous',
      'bible_next': 'Next',
      'acc_account': 'Account',
      'acc_my_account': 'My Account',
      'acc_manage_account': 'Manage your account settings',
      'acc_sign_in': 'Sign in to your account',
      'acc_view_messages': 'View your messages',
      'acc_preferences': 'Preferences',
      'acc_customize': 'Customize your experience',
      'acc_learn_more': 'Learn more about the app',
      'acc_loading': 'Loading...',
      'acc_signed_in': 'Signed In',
      'acc_guest_user': 'Guest User',
      'auth_account_info': 'Account Information',
      'auth_email': 'Email',
      'auth_not_provided': 'Not provided',
      'auth_sign_up': 'Sign Up',
      'auth_password': 'Password',
      'auth_confirm_password': 'Confirm Password',
      'auth_forgot_password': 'Forgot Password',
      'auth_reset_password': 'Reset Password',
      'auth_verify_account': 'Verify Account',
      'auth_verify_your_account': 'Verify Your Account',
      'auth_account_created': 'Account created! Please check your email for a verification code.',
      'auth_account_confirmed': 'Account confirmed successfully! Please sign in.',
      'auth_please_enter_email': 'Please enter your email',
      'auth_please_enter_valid_email': 'Please enter a valid email',
      'auth_please_enter_password': 'Please enter a password',
      'auth_please_enter_full_name': 'Please enter your full name',
      'auth_please_confirm_password': 'Please confirm your password',
      'auth_password_min_length': 'Password must be at least 8 characters',
      'auth_password_strong': 'Password must contain uppercase, lowercase and number',
      'auth_passwords_not_match': 'Passwords do not match',
      'auth_already_have_account': 'Already have an account? Login',
      'auth_dont_have_account': 'Don\'t have an account? Sign up',
      'auth_full_name': 'Full Name',
      'auth_gender': 'Gender',
      'auth_edit_profile': 'Edit Profile',
      'auth_logout': 'Logout',
      'auth_verification_code': 'Verification Code',
      'auth_new_password': 'New Password',
      'auth_settings_saved': 'Settings saved successfully!',
      'auth_login_successful': 'Login successful!',
      'auth_logout_successful': 'You have been logged out successfully',
      'auth_error_signing_out': 'Error signing out',
      'auth_profile_updated': 'Profile updated successfully!',
      'auth_password_reset_successful': 'Password reset successfully! Please sign in.',
      'auth_account_confirmed_successful': 'Account confirmed successfully! Please sign in.',
      'auth_verification_code_sent': 'A new verification code has been sent to your email.',
      'auth_verses_copied': 'verse(s) copied to clipboard',
      'auth_account_created': 'Account created! Please check your email for a verification code.',
      'auth_forgot_password': 'Forgot Password?',
      'auth_dont_have_account': "Don't have an account? Sign up",
      'auth_save_changes': 'Save Changes',
      'auth_reset_password': 'Reset Password',
      'auth_verify_account': 'Verify Your Account',
      'auth_enter_6_digit_code': 'Enter the 6-digit code',
      'auth_please_enter_verification_code': 'Please enter the verification code',
      'auth_please_enter_valid_verification_code': 'Please enter a valid verification code',
      'auth_please_enter_new_password': 'Please enter your new password',
      'auth_didnt_receive_code': "Didn't receive the code? Resend",
      'auth_verification_code_sent_info': 'A verification code has been sent to your email. Please enter it below.',
      'home_chat_with_church': 'Chat with Father',
      'chat_login_required': 'Login Required',
      'chat_login_to_chat': 'Please log in to start chatting with Father.',
      'chat_no_messages': 'No messages yet',
      'chat_start_conversation': 'Start a conversation by sending a message below.',
      'chat_type_message': 'Type your message...',
      'auth_logout_confirmation': 'Are you sure you want to log out?',
      'auth_cancel': 'Cancel',
    },
    'ar': {
      'app_name': 'China Coptic',
      'home_page': 'الرئيسية',
      'bible_page': 'الكتاب المقدس',
      'catalogue_page': 'الفهرس',
      'listen_page': 'استمع',
      'account_page': 'الحساب',
      'cat_agpeya': 'الأجبية',
      'cat_psalmody': 'الإبصلمودية',
      'cat_liturgies': 'القداسات',
      'cat_melodies': 'الألحان',
      'cat_clergy': 'الإكليروس',
      'cat_readings': 'القراءات',
      'cat_index': 'الفهرس',
      'cat_special': 'خاص',
      'read_vespers': 'عشية',
      'read_matins': 'باكر',
      'read_Liturgy': 'القداس',
      'read_antiphonary': 'الأنطيفناري',
      'acc_login': 'تسجيل الدخول',
      'acc_messages': 'الرسائل',
      'acc_favorite': 'المفضلة',
      'acc_settings': 'الإعدادات',
      'acc_aboutapp': 'عن التطبيق',
      'acc_feedback': 'ملاحظات',
      'acc_contactus': 'اتصل بنا',
      'sett_fontsize': 'حجم الخط',
      'sett_fontstyle': 'نمط الخط',
      'sett_fontcolor': 'لون الخط',
      'sett_defaultlang': 'اللغة الافتراضية',
      'sett_savesettings': 'حفظ الإعدادات',
      'sett_choosecolor': 'اختر اللون',
      'sett_appearance': 'المظهر',
      'sett_reading_settings': 'إعدادات القراءة',
      'sett_language_settings': 'إعدادات اللغة',
      'sett_default_language': 'اللغة الافتراضية',
      'sett_display_language_1': 'لغة العرض 1',
      'sett_display_language_2': 'لغة العرض 2',
      'agpeya_first': 'الساعة الأولى',
      'agpeya_third': 'الساعة الثالثة',
      'agpeya_sixth': 'الساعة السادسة',
      'agpeya_nineth': 'الساعة التاسعة',
      'agpeya_eleventh': 'الساعة الحادية عشر',
      'agpeya_twelfth': 'الساعة الثانية عشر',
      'agpeya_viel': 'صلاة الحجاب',
      'agpeya_midnight': 'صلاة نصف الليل',
      'agpeya_prayers': 'صلوات',
      'settings_saved_pop': 'تم حفظ الإعدادات، يرجى إعادة تشغيل التطبيق',
      "reader_page_sections_header": "الأقسام",
      "home_father_message": "رسالة من الأب",
      "home_read_bible": "اقرأ الكتاب المقدس",
      "home_listen_to_sermon": "استمع إلى العظة",
      "home_readings": "القراءات",
      "home_agpeya": "الأجبية",
      "home_todays_readings": "قراءات اليوم",
      "sett_disp_lang1": "لغة العرض 1",
      "sett_disp_lang2": "لغة العرض 2",
      "bible_old_testament": "العهد القديم",
      "bible_new_testament": "العهد الجديد",
      "bible_chapters": "الفصول",
      "bible_genesis": "التكوين",
      "bible_exodus": "الخروج",
      "bible_leviticus": "اللاويين",
      "bible_numbers": "العدد",
      "bible_deuteronomy": "التثنية",
      "bible_joshua": "يشوع",
      "bible_judges": "القضاة",
      "bible_ruth": "راعوث",
      "bible_1_samuel": "صموئيل الأول",
      "bible_2_samuel": "صموئيل الثاني",
      "bible_1_kings": "الملوك الأول",
      "bible_2_kings": "الملوك الثاني",
      "bible_1_chronicles": "أخبار الأيام الأول",
      "bible_2_chronicles": "أخبار الأيام الثاني",
      "bible_ezra": "عزرا",
      "bible_nehemiah": "نحميا",
      "bible_esther": "أستير",
      "bible_job": "أيوب",
      "bible_psalms": "المزامير",
      "bible_proverbs": "الأمثال",
      "bible_ecclesiastes": "الجامعة",
      "bible_song_of_songs": "نشيد الأنشاد",
      "bible_isaiah": "إشعياء",
      "bible_jeremiah": "إرميا",
      "bible_lamentations": "مراثي إرميا",
      "bible_ezekiel": "حزقيال",
      "bible_daniel": "دانيال",
      "bible_hosea": "هوشع",
      "bible_joel": "يوئيل",
      "bible_amos": "عاموس",
      "bible_obadiah": "عوبديا",
      "bible_jonah": "يونان",
      "bible_micah": "ميخا",
      "bible_nahum": "ناحوم",
      "bible_habakkuk": "حبقوق",
      "bible_zephaniah": "صفنيا",
      "bible_haggai": "حجي",
      "bible_zechariah": "زكريا",
      "bible_malachi": "ملاخي",
      "bible_matthew": "متى",
      "bible_mark": "مرقس",
      "bible_luke": "لوقا",
      "bible_john": "يوحنا",
      "bible_acts": "أعمال الرسل",
      "bible_romans": "رومية",
      "bible_1_corinthians": "كورنثوس الأولى",
      "bible_2_corinthians": "كورنثوس الثانية",
      "bible_galatians": "غلاطية",
      "bible_ephesians": "أفسس",
      "bible_philippians": "فيلبي",
      "bible_colossians": "كولوسي",
      "bible_1_thessalonians": "تسالونيكي الأولى",
      "bible_2_thessalonians": "تسالونيكي الثانية",
      "bible_1_timothy": "تيموثاوس الأولى",
      "bible_2_timothy": "تيموثاوس الثانية",
      "bible_titus": "تيطس",
      "bible_philemon": "فليمون",
      "bible_hebrews": "العبرانيين",
      "bible_james": "يعقوب",
      "bible_1_peter": "بطرس الأولى",
      "bible_2_peter": "بطرس الثانية",
      "bible_1_john": "يوحنا الأولى",
      "bible_2_john": "يوحنا الثانية",
      "bible_3_john": "يوحنا الثالثة",
      "bible_jude": "يهوذا",
      "bible_revelation": "رؤيا يوحنا",
      "bible_tobit": "طوبيا",
      "bible_judith": "يهوديت",
      "bible_wisdom": "سفر الحكمة",
      "bible_sirach": "سفر يشوع بن سيراخ",
      "bible_baruch": "سفر باروخ",
      "bible_1_maccabees": "المكابيين الأول",
      "bible_2_maccabees": "المكابيين الثاني",
      "bible_prayer_of_manasseh": "صلاة منسى الملك",
      "bible_search_hint": "البحث في الكتاب المقدس...",
      "bible_previous": "السابق",
      "bible_next": "التالي",
      "acc_account": "الحساب",
      "acc_my_account": "حسابي",
      "acc_manage_account": "إدارة إعدادات حسابك",
      "acc_sign_in": "تسجيل الدخول إلى حسابك",
      "acc_view_messages": "عرض رسائلك",
      "acc_preferences": "التفضيلات",
      "acc_customize": "تخصيص تجربتك",
      "acc_learn_more": "تعرف على المزيد حول التطبيق",
      "acc_loading": "جاري التحميل...",
      "acc_signed_in": "تم تسجيل الدخول",
      "acc_guest_user": "مستخدم ضيف",
      "auth_account_info": "معلومات الحساب",
      "auth_email": "البريد الإلكتروني",
      "auth_not_provided": "غير متوفر",
      "auth_sign_up": "إنشاء حساب",
      "auth_password": "كلمة المرور",
      "auth_confirm_password": "تأكيد كلمة المرور",
      "auth_forgot_password": "نسيت كلمة المرور",
      "auth_reset_password": "إعادة تعيين كلمة المرور",
      "auth_verify_account": "التحقق من الحساب",
      "auth_verify_your_account": "تحقق من حسابك",
      "auth_account_created": "تم إنشاء الحساب! يرجى التحقق من بريدك الإلكتروني للحصول على رمز التحقق.",
      "auth_account_confirmed": "تم تأكيد الحساب بنجاح! يرجى تسجيل الدخول.",
      "auth_please_enter_email": "يرجى إدخال بريدك الإلكتروني",
      "auth_please_enter_valid_email": "يرجى إدخال بريد إلكتروني صحيح",
      "auth_please_enter_password": "يرجى إدخال كلمة مرور",
      "auth_please_enter_full_name": "يرجى إدخال اسمك الكامل",
      "auth_please_confirm_password": "يرجى تأكيد كلمة المرور",
      "auth_password_min_length": "يجب أن تكون كلمة المرور 8 أحرف على الأقل",
      "auth_password_strong": "يجب أن تحتوي كلمة المرور على أحرف كبيرة وصغيرة ورقم",
      "auth_passwords_not_match": "كلمات المرور غير متطابقة",
      "auth_already_have_account": "لديك حساب بالفعل؟ تسجيل الدخول",
      "auth_dont_have_account": "ليس لديك حساب؟ إنشاء حساب",
      "auth_full_name": "الاسم الكامل",
      "auth_gender": "الجنس",
      "auth_edit_profile": "تعديل الملف الشخصي",
      "auth_logout": "تسجيل الخروج",
      "auth_verification_code": "رمز التحقق",
      "auth_new_password": "كلمة مرور جديدة",
      "auth_settings_saved": "تم حفظ الإعدادات بنجاح!",
      "auth_login_successful": "تم تسجيل الدخول بنجاح!",
      "auth_logout_successful": "تم تسجيل الخروج بنجاح",
      "auth_error_signing_out": "خطأ في تسجيل الخروج",
      "auth_profile_updated": "تم تحديث الملف الشخصي بنجاح!",
      "auth_password_reset_successful": "تم إعادة تعيين كلمة المرور بنجاح! يرجى تسجيل الدخول.",
      "auth_account_confirmed_successful": "تم تأكيد الحساب بنجاح! يرجى تسجيل الدخول.",
      "auth_verification_code_sent": "تم إرسال رمز تحقق جديد إلى بريدك الإلكتروني.",
      "auth_verses_copied": "آية/آيات تم نسخها إلى الحافظة",
      "auth_account_created": "تم إنشاء الحساب! يرجى التحقق من بريدك الإلكتروني للحصول على رمز التحقق.",
      "auth_forgot_password": "نسيت كلمة المرور؟",
      "auth_dont_have_account": "ليس لديك حساب؟ سجل",
      "auth_save_changes": "حفظ التغييرات",
      "auth_reset_password": "إعادة تعيين كلمة المرور",
      "auth_verify_account": "تحقق من حسابك",
      "auth_enter_6_digit_code": "أدخل رمز التحقق المكون من 6 أرقام",
      "auth_please_enter_verification_code": "يرجى إدخال رمز التحقق",
      "auth_please_enter_valid_verification_code": "يرجى إدخال رمز تحقق صحيح",
      "home_chat_with_church": "الدردشة مع الأب",
      "chat_login_required": "تسجيل الدخول مطلوب",
      "chat_login_to_chat": "يرجى تسجيل الدخول لبدء الدردشة مع مجتمع الكنيسة.",
      "chat_no_messages": "لا توجد رسائل بعد",
      "chat_start_conversation": "ابدأ محادثة بإرسال رسالة أدناه.",
      "chat_type_message": "اكتب رسالتك...",
      "auth_logout_confirmation": "هل أنت متأكد من أنك تريد تسجيل الخروج؟",
      "auth_cancel": "إلغاء",
      "auth_please_enter_new_password": "يرجى إدخال كلمة المرور الجديدة",
      "auth_didnt_receive_code": "لم تستلم الرمز؟ إعادة إرسال",
      "auth_verification_code_sent_info": "تم إرسال رمز تحقق إلى بريدك الإلكتروني. يرجى إدخاله أدناه.",
    },
    'zh_hant': {
      'app_name': 'China Coptic',
      'home_page': '主頁',
      'bible_page': '聖經',
      'catalogue_page': '目錄',
      'listen_page': '聽',
      'account_page': '帳戶',
      'cat_agpeya': '時辰禱文',
      'cat_psalmody': '讚美詩',
      'cat_liturgies': '聖祭禮',
      'cat_melodies': '聖歌',
      'cat_clergy': '神職人員',
      'cat_readings': '讀經',
      'cat_index': '索引',
      'cat_special': '特別',
      'read_vespers': '晚禱',
      'read_matins': '晨禱',
      'read_Liturgy': '感恩祭',
      'read_antiphonary': '輪唱詩集',
      'acc_login': '登入',
      'acc_messages': '訊息',
      'acc_favorite': '收藏',
      'acc_settings': '設定',
      'acc_aboutapp': '關於應用',
      'acc_feedback': '反饋',
      'acc_contactus': '聯絡我們',
      'sett_fontsize': '字體大小',
      'sett_fontstyle': '字體樣式',
      'sett_fontcolor': '字體顏色',
      'sett_defaultlang': '預設語言',
      'sett_savesettings': '保存設定',
      'sett_choosecolor': '選擇顏色',
      'sett_appearance': '外觀',
      'sett_reading_settings': '閱讀設定',
      'sett_language_settings': '語言設定',
      'sett_default_language': '預設語言',
      'sett_display_language_1': '顯示語言 1',
      'sett_display_language_2': '顯示語言 2',
      'agpeya_first': '第一時辰',
      'agpeya_third': '第三時辰',
      'agpeya_sixth': '第六時辰',
      'agpeya_nineth': '第九時辰',
      'agpeya_eleventh': '第十一時辰',
      'agpeya_twelfth': '第十二時辰',
      'agpeya_viel': '面紗祈禱',
      'agpeya_midnight': '午夜祈禱',
      'agpeya_prayers': '禱告',
      'settings_saved_pop': '設定已儲存，請重新啟動應用程式。',
      "reader_page_sections_header": "章節",
      "home_father_message": "神父的訊息",
      "home_read_bible": "閱讀聖經",
      "home_listen_to_sermon": "聆聽講道",
      "home_readings": "經文閱讀",
      "home_agpeya": "阿格佩亞祈禱書",
      "home_todays_readings": "今日經文",
      "sett_disp_lang1": "顯示語言1",
      "sett_disp_lang2": "顯示語言2",
      "bible_old_testament": "舊約",
      "bible_new_testament": "新約",
      "bible_chapters": "章節",
      "bible_genesis": "創世記",
      "bible_exodus": "出埃及記",
      "bible_leviticus": "利未記",
      "bible_numbers": "民數記",
      "bible_deuteronomy": "申命記",
      "bible_joshua": "約書亞記",
      "bible_judges": "士師記",
      "bible_ruth": "路得記",
      "bible_1_samuel": "撒母耳記上",
      "bible_2_samuel": "撒母耳記下",
      "bible_1_kings": "列王紀上",
      "bible_2_kings": "列王紀下",
      "bible_1_chronicles": "歷代志上",
      "bible_2_chronicles": "歷代志下",
      "bible_ezra": "以斯拉記",
      "bible_nehemiah": "尼希米記",
      "bible_esther": "以斯帖記",
      "bible_job": "約伯記",
      "bible_psalms": "詩篇",
      "bible_proverbs": "箴言",
      "bible_ecclesiastes": "傳道書",
      "bible_song_of_songs": "雅歌",
      "bible_isaiah": "以賽亞書",
      "bible_jeremiah": "耶利米書",
      "bible_lamentations": "耶利米哀歌",
      "bible_ezekiel": "以西結書",
      "bible_daniel": "但以理書",
      "bible_hosea": "何西阿書",
      "bible_joel": "約珥書",
      "bible_amos": "阿摩司書",
      "bible_obadiah": "俄巴底亞書",
      "bible_jonah": "約拿書",
      "bible_micah": "彌迦書",
      "bible_nahum": "那鴻書",
      "bible_habakkuk": "哈巴谷書",
      "bible_zephaniah": "西番雅書",
      "bible_haggai": "哈該書",
      "bible_zechariah": "撒迦利亞書",
      "bible_malachi": "瑪拉基書",
      "bible_matthew": "馬太福音",
      "bible_mark": "馬可福音",
      "bible_luke": "路加福音",
      "bible_john": "約翰福音",
      "bible_acts": "使徒行傳",
      "bible_romans": "羅馬書",
      "bible_1_corinthians": "哥林多前書",
      "bible_2_corinthians": "哥林多後書",
      "bible_galatians": "加拉太書",
      "bible_ephesians": "以弗所書",
      "bible_philippians": "腓立比書",
      "bible_colossians": "歌羅西書",
      "bible_1_thessalonians": "帖撒羅尼迦前書",
      "bible_2_thessalonians": "帖撒羅尼迦後書",
      "bible_1_timothy": "提摩太前書",
      "bible_2_timothy": "提摩太後書",
      "bible_titus": "提多書",
      "bible_philemon": "腓利門書",
      "bible_hebrews": "希伯來書",
      "bible_james": "雅各書",
      "bible_1_peter": "彼得前書",
      "bible_2_peter": "彼得後書",
      "bible_1_john": "約翰一書",
      "bible_2_john": "約翰二書",
      "bible_3_john": "約翰三書",
      "bible_jude": "猶大書",
      "bible_revelation": "啟示錄",
      "bible_tobit": "多俾亞傳",
      "bible_judith": "友弟德傳",
      "bible_wisdom": "智慧篇",
      "bible_sirach": "德訓篇",
      "bible_baruch": "巴路克書",
      "bible_1_maccabees": "瑪加伯上",
      "bible_2_maccabees": "瑪加伯下",
      "bible_prayer_of_manasseh": "瑪拿西禱詞",
      "bible_search_hint": "在聖經中搜尋...",
      "bible_previous": "上一章",
      "bible_next": "下一章",
      "acc_account": "帳戶",
      "acc_my_account": "我的帳戶",
      "acc_manage_account": "管理您的帳戶設定",
      "acc_sign_in": "登入您的帳戶",
      "acc_view_messages": "查看您的訊息",
      "acc_preferences": "偏好設定",
      "acc_customize": "自訂您的體驗",
      "acc_learn_more": "了解更多關於應用程式",
      "acc_loading": "載入中...",
      "acc_signed_in": "已登入",
      "acc_guest_user": "訪客使用者",
      "auth_account_info": "帳戶資訊",
      "auth_email": "電子郵件",
      "auth_not_provided": "未提供",
      "auth_sign_up": "註冊",
      "auth_password": "密碼",
      "auth_confirm_password": "確認密碼",
      "auth_forgot_password": "忘記密碼",
      "auth_reset_password": "重設密碼",
      "auth_verify_account": "驗證帳戶",
      "auth_verify_your_account": "驗證您的帳戶",
      "auth_account_created": "帳戶已建立！請檢查您的電子郵件以取得驗證碼。",
      "auth_account_confirmed": "帳戶確認成功！請登入。",
      "auth_please_enter_email": "請輸入您的電子郵件",
      "auth_please_enter_valid_email": "請輸入有效的電子郵件",
      "auth_please_enter_password": "請輸入密碼",
      "auth_please_enter_full_name": "請輸入您的全名",
      "auth_please_confirm_password": "請確認您的密碼",
      "auth_password_min_length": "密碼至少需要8個字元",
      "auth_password_strong": "密碼必須包含大寫、小寫字母和數字",
      "auth_passwords_not_match": "密碼不相符",
      "auth_already_have_account": "已有帳戶？登入",
      "auth_dont_have_account": "沒有帳戶？註冊",
      "auth_full_name": "全名",
      "auth_gender": "性別",
      "auth_edit_profile": "編輯個人資料",
      "auth_logout": "登出",
      "auth_verification_code": "驗證碼",
      "auth_new_password": "新密碼",
      "auth_settings_saved": "設定已成功儲存！",
      "auth_login_successful": "登入成功！",
      "auth_logout_successful": "您已成功登出",
      "auth_error_signing_out": "登出時發生錯誤",
      "auth_profile_updated": "個人資料已成功更新！",
      "auth_password_reset_successful": "密碼重設成功！請登入。",
      "auth_account_confirmed_successful": "帳戶確認成功！請登入。",
      "auth_verification_code_sent": "新的驗證碼已發送到您的電子郵件。",
      "auth_verses_copied": "節經文已複製到剪貼簿",
      "auth_account_created": "帳戶已建立！請檢查您的電子郵件以獲取驗證碼。",
      "auth_forgot_password": "忘記密碼？",
      "auth_dont_have_account": "沒有帳戶？註冊",
      "auth_save_changes": "儲存變更",
      "auth_reset_password": "重置密碼",
      "auth_verify_account": "驗證您的帳戶",
      "auth_enter_6_digit_code": "輸入6位數驗證碼",
      "auth_please_enter_verification_code": "請輸入驗證碼",
      "auth_please_enter_valid_verification_code": "請輸入有效的驗證碼",
      "auth_please_enter_new_password": "請輸入您的新密碼",
      "auth_didnt_receive_code": "沒收到驗證碼？重新發送",
      "auth_verification_code_sent_info": "驗證碼已發送到您的電子郵件。請在下方輸入。",
      "home_chat_with_church": "Chat with Church",
      "chat_login_required": "Login Required",
      "chat_login_to_chat": "Please log in to start chatting with the church community.",
      "chat_no_messages": "No messages yet",
      "chat_start_conversation": "Start a conversation by sending a message below.",
      "chat_type_message": "Type your message...",
    },
    'zh_hans': {
      'app_name': 'China Coptic',
      'home_page': '主页',
      'bible_page': '圣经',
      'catalogue_page': '目录',
      'listen_page': '听',
      'account_page': '我的',
      'cat_agpeya': '时辰祷文',
      'cat_psalmody': '赞美诗',
      'cat_liturgies': '圣祭礼',
      'cat_melodies': '圣歌',
      'cat_clergy': '神职人员',
      'cat_readings': '读经',
      'cat_index': '索引',
      'cat_special': '特别',
      'read_vespers': '晚祷',
      'read_matins': '晨祷',
      'read_Liturgy': '感恩祭',
      'read_antiphonary': '轮唱诗集',
      'acc_login': '登录',
      'acc_messages': '消息',
      'acc_favorite': '收藏',
      'acc_settings': '设置',
      'acc_aboutapp': '关于应用',
      'acc_feedback': '反馈',
      'acc_contactus': '联系我们',
      'sett_fontsize': '字体大小',
      'sett_fontstyle': '字体样式',
      'sett_fontcolor': '字体颜色',
      'sett_defaultlang': '默认语言',
      'sett_savesettings': '保存设置',
      'sett_choosecolor': '选择颜色',
      'sett_appearance': '外观',
      'sett_reading_settings': '阅读设置',
      'sett_language_settings': '语言设置',
      'sett_default_language': '默认语言',
      'sett_display_language_1': '显示语言 1',
      'sett_display_language_2': '显示语言 2',
      'agpeya_first': '第一时辰',
      'agpeya_third': '第三时辰',
      'agpeya_sixth': '第六时辰',
      'agpeya_nineth': '第九时辰',
      'agpeya_eleventh': '第十一时辰',
      'agpeya_twelfth': '第十二时辰',
      'agpeya_viel': '面纱祈祷',
      'agpeya_midnight': '午夜祈祷',
      'agpeya_prayers': '祷告',
      'settings_saved_pop': '设置已保存，请重新启动应用程序。',
      "reader_page_sections_header": "章节",
      "home_father_message": "神父寄语",
      "home_read_bible": "阅读圣经",
      "home_listen_to_sermon": "听讲道",
      "home_readings": "经文阅读",
      "home_agpeya": "阿格佩亚祈祷书",
      "home_todays_readings": "今日经文",
      "sett_disp_lang1": "显示语言1",
      "sett_disp_lang2": "显示语言2",
      "bible_old_testament": "旧约",
      "bible_new_testament": "新约",
      "bible_chapters": "章节",
      "bible_genesis": "创世记",
      "bible_exodus": "出埃及记",
      "bible_leviticus": "利未记",
      "bible_numbers": "民数记",
      "bible_deuteronomy": "申命记",
      "bible_joshua": "约书亚记",
      "bible_judges": "士师记",
      "bible_ruth": "路得记",
      "bible_1_samuel": "撒母耳记上",
      "bible_2_samuel": "撒母耳记下",
      "bible_1_kings": "列王纪上",
      "bible_2_kings": "列王纪下",
      "bible_1_chronicles": "历代志上",
      "bible_2_chronicles": "历代志下",
      "bible_ezra": "以斯拉记",
      "bible_nehemiah": "尼希米记",
      "bible_esther": "以斯帖记",
      "bible_job": "约伯记",
      "bible_psalms": "诗篇",
      "bible_proverbs": "箴言",
      "bible_ecclesiastes": "传道书",
      "bible_song_of_songs": "雅歌",
      "bible_isaiah": "以赛亚书",
      "bible_jeremiah": "耶利米书",
      "bible_lamentations": "耶利米哀歌",
      "bible_ezekiel": "以西结书",
      "bible_daniel": "但以理书",
      "bible_hosea": "何西阿书",
      "bible_joel": "约珥书",
      "bible_amos": "阿摩司书",
      "bible_obadiah": "俄巴底亚书",
      "bible_jonah": "约拿书",
      "bible_micah": "弥迦书",
      "bible_nahum": "那鸿书",
      "bible_habakkuk": "哈巴谷书",
      "bible_zephaniah": "西番雅书",
      "bible_haggai": "哈该书",
      "bible_zechariah": "撒迦利亚书",
      "bible_malachi": "玛拉基书",
      "bible_matthew": "马太福音",
      "bible_mark": "马可福音",
      "bible_luke": "路加福音",
      "bible_john": "约翰福音",
      "bible_acts": "使徒行传",
      "bible_romans": "罗马书",
      "bible_1_corinthians": "哥林多前书",
      "bible_2_corinthians": "哥林多后书",
      "bible_galatians": "加拉太书",
      "bible_ephesians": "以弗所书",
      "bible_philippians": "腓立比书",
      "bible_colossians": "歌罗西书",
      "bible_1_thessalonians": "帖撒罗尼迦前书",
      "bible_2_thessalonians": "帖撒罗尼迦后书",
      "bible_1_timothy": "提摩太前书",
      "bible_2_timothy": "提摩太后书",
      "bible_titus": "提多书",
      "bible_philemon": "腓利门书",
      "bible_hebrews": "希伯来书",
      "bible_james": "雅各书",
      "bible_1_peter": "彼得前书",
      "bible_2_peter": "彼得后书",
      "bible_1_john": "约翰一书",
      "bible_2_john": "约翰二书",
      "bible_3_john": "约翰三书",
      "bible_jude": "犹大书",
      "bible_revelation": "启示录",
      "bible_tobit": "多俾亚传",
      "bible_judith": "友弟德传",
      "bible_wisdom": "智慧篇",
      "bible_sirach": "德训篇",
      "bible_baruch": "巴路克书",
      "bible_1_maccabees": "玛加伯上",
      "bible_2_maccabees": "玛加伯下",
      "bible_prayer_of_manasseh": "玛拿西祷词",
      "bible_search_hint": "在圣经中搜索...",
      "bible_previous": "上一章",
      "bible_next": "下一章",
      "acc_account": "账户",
      "acc_my_account": "我的账户",
      "acc_manage_account": "管理您的账户设置",
      "acc_sign_in": "登录您的账户",
      "acc_view_messages": "查看您的消息",
      "acc_preferences": "偏好设置",
      "acc_customize": "自定义您的体验",
      "acc_learn_more": "了解更多关于应用程序",
      "acc_loading": "加载中...",
      "acc_signed_in": "已登录",
      "acc_guest_user": "访客用户",
      "auth_account_info": "账户信息",
      "auth_email": "电子邮件",
      "auth_not_provided": "未提供",
      "auth_sign_up": "注册",
      "auth_password": "密码",
      "auth_confirm_password": "确认密码",
      "auth_forgot_password": "忘记密码",
      "auth_reset_password": "重置密码",
      "auth_verify_account": "验证账户",
      "auth_verify_your_account": "验证您的账户",
      "auth_account_created": "账户已创建！请检查您的电子邮件以获取验证码。",
      "auth_account_confirmed": "账户确认成功！请登录。",
      "auth_please_enter_email": "请输入您的电子邮件",
      "auth_please_enter_valid_email": "请输入有效的电子邮件",
      "auth_please_enter_password": "请输入密码",
      "auth_please_enter_full_name": "请输入您的全名",
      "auth_please_confirm_password": "请确认您的密码",
      "auth_password_min_length": "密码至少需要8个字符",
      "auth_password_strong": "密码必须包含大写、小写字母和数字",
      "auth_passwords_not_match": "密码不匹配",
      "auth_already_have_account": "已有账户？登录",
      "auth_dont_have_account": "没有账户？注册",
      "auth_full_name": "全名",
      "auth_gender": "性别",
      "auth_edit_profile": "编辑个人资料",
      "auth_logout": "登出",
      "auth_verification_code": "验证码",
      "auth_new_password": "新密码",
      "auth_settings_saved": "设置已成功保存！",
      "auth_login_successful": "登录成功！",
      "auth_logout_successful": "您已成功登出",
      "auth_error_signing_out": "登出时发生错误",
      "auth_profile_updated": "个人资料已成功更新！",
      "auth_password_reset_successful": "密码重置成功！请登录。",
      "auth_account_confirmed_successful": "账户确认成功！请登录。",
      "auth_verification_code_sent": "新的验证码已发送到您的电子邮件。",
      "auth_verses_copied": "节经文已复制到剪贴板",
      "auth_account_created": "账户已创建！请检查您的电子邮件以获取验证码。",
      "auth_forgot_password": "忘记密码？",
      "auth_dont_have_account": "没有账户？注册",
      "auth_save_changes": "保存更改",
      "auth_reset_password": "重置密码",
      "auth_verify_account": "验证您的账户",
      "auth_enter_6_digit_code": "输入6位数字验证码",
      "auth_please_enter_verification_code": "请输入验证码",
      "auth_please_enter_valid_verification_code": "请输入有效的验证码",
      "auth_please_enter_new_password": "请输入您的新密码",
      "auth_didnt_receive_code": "没收到验证码？重新发送",
      "auth_verification_code_sent_info": "验证码已发送到您的电子邮件。请在下方输入。",
      "home_chat_with_church": "Chat with Church",
      "chat_login_required": "Login Required",
      "chat_login_to_chat": "Please log in to start chatting with the church community.",
      "chat_no_messages": "No messages yet",
      "chat_start_conversation": "Start a conversation by sending a message below.",
      "chat_type_message": "Type your message...",
    },
    'coptic': {
      'app_name': 'China Coptic',
      'home_page': 'Home',
      'bible_page': 'Bible',
      'catalogue_page': 'Catalogue',
      'listen_page': 'Listen',
      'account_page': 'Account',
      'cat_agpeya': 'Agpeya',
      'cat_psalmody': 'Psalmody',
      'cat_liturgies': 'Liturgies',
      'cat_melodies': 'Melodies',
      'cat_clergy': 'Clergy',
      'cat_readings': 'Readings',
      'cat_index': 'Index',
      'cat_special': 'Special',
      'read_vespers': 'Vespers',
      'read_matins': 'Matins',
      'read_Liturgy': 'Liturgy',
      'read_antiphonary': 'Antiphonary',
      'acc_login': 'Login',
      'acc_messages': 'Messages',
      'acc_favorite': 'Favorite',
      'acc_settings': 'Settings',
      'acc_aboutapp': 'About App',
      'acc_feedback': 'Feedback',
      'acc_contactus': 'Contact Us',
      'sett_fontsize': 'Font Size',
      'sett_fontstyle': 'Font Style',
      'sett_fontcolor': 'Font Color',
      'sett_defaultlang': 'Default Language',
      'sett_savesettings': 'Save Settings',
      'sett_choosecolor': 'Choose Color',
      'agpeya_first': '1st Hour',
      'agpeya_third': '3rd Hour',
      'agpeya_sixth': '6th Hour',
      'agpeya_nineth': '9th Hour',
      'agpeya_eleventh': '11th Hour',
      'agpeya_twelfth': '12th Hour',
      'agpeya_viel': 'Veil Prayer',
      'agpeya_midnight': 'Midnight Prayer',
      'agpeya_prayers': 'Prayers',
      'settings_saved_pop': 'Settings saved, please restart the app.',
      'reader_page_sections_header': 'Sections',
      'home_father_message': 'Father Message',
      'home_read_bible': 'Read Bible',
      'home_listen_to_sermon': 'Listen to Sermon',
      'home_readings': 'Readings',
      'home_agpeya': 'Agpeya',
      'home_todays_readings': 'Today Readings',
      'sett_disp_lang1': 'Display Language 1',
      'sett_disp_lang2': 'Display Language 2',
      'bible_old_testament': 'Old Testament',
      'bible_new_testament': 'New Testament',
      'bible_chapters': 'Chapters',
      'bible_search_hint': 'Search in Bible...',
      'bible_previous': 'Previous',
      'bible_next': 'Next',
      'acc_account': 'Account',
      'acc_my_account': 'My Account',
      'acc_manage_account': 'Manage your account settings',
      'acc_sign_in': 'Sign in to your account',
      'acc_view_messages': 'View your messages',
      'acc_preferences': 'Preferences',
      'acc_customize': 'Customize your experience',
      'acc_learn_more': 'Learn more about the app',
      'acc_loading': 'Loading...',
      'acc_signed_in': 'Signed In',
      'acc_guest_user': 'Guest User',
      'auth_account_info': 'Account Info',
      'auth_email': 'Email',
      'auth_not_provided': 'Not Provided',
      'auth_sign_up': 'Sign Up',
      'auth_password': 'Password',
      'auth_confirm_password': 'Confirm Password',
      'auth_forgot_password': 'Forgot Password',
      'auth_reset_password': 'Reset Password',
      'auth_verify_account': 'Verify Account',
      'auth_verify_your_account': 'Verify Your Account',
      'auth_account_created': 'Account created! Please check your email for a verification code.',
      'auth_account_confirmed': 'Account confirmed successfully! Please sign in.',
      'auth_please_enter_email': 'Please enter your email',
      'auth_please_enter_valid_email': 'Please enter a valid email',
      'auth_please_enter_password': 'Please enter a password',
      'auth_please_enter_full_name': 'Please enter your full name',
      'auth_please_confirm_password': 'Please confirm your password',
      'auth_password_min_length': 'Password must be at least 8 characters',
      'auth_password_strong': 'Password must contain uppercase, lowercase and number',
      'auth_passwords_not_match': 'Passwords do not match',
      'auth_already_have_account': 'Already have an account? Login',
      'auth_dont_have_account': "Don't have an account? Sign up",
      'auth_full_name': 'Full Name',
      'auth_gender': 'Gender',
      'auth_edit_profile': 'Edit Profile',
      'auth_logout': 'Logout',
      'auth_verification_code': 'Verification Code',
      'auth_new_password': 'New Password',
      'auth_settings_saved': 'Settings saved successfully!',
      'auth_login_successful': 'Login successful!',
      'auth_logout_successful': 'You have been logged out successfully',
      'auth_error_signing_out': 'Error signing out',
      'auth_profile_updated': 'Profile updated successfully!',
      'auth_password_reset_successful': 'Password reset successfully! Please sign in.',
      'auth_account_confirmed_successful': 'Account confirmed successfully! Please sign in.',
      'auth_verification_code_sent': 'A new verification code has been sent to your email.',
      'auth_verses_copied': 'verse(s) copied to clipboard',
      'auth_account_created': 'Account created! Please check your email for a verification code.',
      'auth_forgot_password': 'Forgot Password?',
      'auth_dont_have_account': "Don't have an account? Sign up",
      'auth_save_changes': 'Save Changes',
      'auth_reset_password': 'Reset Password',
      'auth_verify_account': 'Verify Your Account',
      'auth_enter_6_digit_code': 'Enter the 6-digit code',
      'auth_please_enter_verification_code': 'Please enter the verification code',
      'auth_please_enter_valid_verification_code': 'Please enter a valid verification code',
      'auth_please_enter_new_password': 'Please enter your new password',
      'auth_didnt_receive_code': "Didn't receive the code? Resend",
      'auth_verification_code_sent_info': 'A verification code has been sent to your email. Please enter it below.',
      'sett_appearance': 'Appearance',
      'sett_reading_settings': 'Reading Settings',
      'sett_language_settings': 'Language Settings',
      'sett_default_language': 'Default Language',
      'sett_display_language_1': 'Display Language 1',
      'sett_display_language_2': 'Display Language 2',
      'bible_genesis': 'Genesis',
      'bible_exodus': 'Exodus',
      'bible_leviticus': 'Leviticus',
      'bible_numbers': 'Numbers',
      'bible_deuteronomy': 'Deuteronomy',
      'bible_joshua': 'Joshua',
      'bible_judges': 'Judges',
      'bible_ruth': 'Ruth',
      'bible_1_samuel': '1 Samuel',
      'bible_2_samuel': '2 Samuel',
      'bible_1_kings': '1 Kings',
      'bible_2_kings': '2 Kings',
      'bible_1_chronicles': '1 Chronicles',
      'bible_2_chronicles': '2 Chronicles',
      'bible_ezra': 'Ezra',
      'bible_nehemiah': 'Nehemiah',
      'bible_esther': 'Esther',
      'bible_job': 'Job',
      'bible_psalms': 'Psalms',
      'bible_proverbs': 'Proverbs',
      'bible_ecclesiastes': 'Ecclesiastes',
      'bible_song_of_songs': 'Song of Songs',
      'bible_isaiah': 'Isaiah',
      'bible_jeremiah': 'Jeremiah',
      'bible_lamentations': 'Lamentations',
      'bible_ezekiel': 'Ezekiel',
      'bible_daniel': 'Daniel',
      'bible_hosea': 'Hosea',
      'bible_joel': 'Joel',
      'bible_amos': 'Amos',
      'bible_obadiah': 'Obadiah',
      'bible_jonah': 'Jonah',
      'bible_micah': 'Micah',
      'bible_nahum': 'Nahum',
      'bible_habakkuk': 'Habakkuk',
      'bible_zephaniah': 'Zephaniah',
      'bible_haggai': 'Haggai',
      'bible_zechariah': 'Zechariah',
      'bible_malachi': 'Malachi',
      'bible_matthew': 'Matthew',
      'bible_mark': 'Mark',
      'bible_luke': 'Luke',
      'bible_john': 'John',
      'bible_acts': 'Acts',
      'bible_romans': 'Romans',
      'bible_1_corinthians': '1 Corinthians',
      'bible_2_corinthians': '2 Corinthians',
      'bible_galatians': 'Galatians',
      'bible_ephesians': 'Ephesians',
      'bible_philippians': 'Philippians',
      'bible_colossians': 'Colossians',
      'bible_1_thessalonians': '1 Thessalonians',
      'bible_2_thessalonians': '2 Thessalonians',
      'bible_1_timothy': '1 Timothy',
      'bible_2_timothy': '2 Timothy',
      'bible_titus': 'Titus',
      'bible_philemon': 'Philemon',
      'bible_hebrews': 'Hebrews',
      'bible_james': 'James',
      'bible_1_peter': '1 Peter',
      'bible_2_peter': '2 Peter',
      'bible_1_john': '1 John',
      'bible_2_john': '2 John',
      'bible_3_john': '3 John',
      'bible_jude': 'Jude',
      'bible_revelation': 'Revelation',
      'bible_tobit': 'Tobit',
      'bible_judith': 'Judith',
      'bible_wisdom': 'Wisdom of Solomon',
      'bible_sirach': 'Sirach',
      'bible_baruch': 'Baruch',
      'bible_1_maccabees': '1 Maccabees',
      'bible_2_maccabees': '2 Maccabees',
      'bible_prayer_of_manasseh': 'Prayer of Manasseh',
    },
  };
}
