class Values {
  static final Map<String, Map<String, String>> nameValues = {
    'en': {
      'app_name': 'China Coptic',
      'home_page': 'Home',
      'bible_page': 'Bible',
      'catalogue_page': 'Catalogue',
      'listen_page': 'Listen',
      'account_page': 'Mine',
      'cat_agpeya': 'Agpeya',
      'cat_psalmody': 'Psalmody',
      'cat_liturgies': 'Liturgies',
      'cat_melodies': 'Melodies',
      'cat_clergy': 'Clergy',
      'cat_readings': 'Readings',
      'cat_index': 'Index',
      'cat_special': 'Special',
      'read_vespers': 'Vespers',
      'read_matins': 'Matins',
      'read_Liturgy': 'Liturgy',
      'read_antiphonary': 'Antiphonary',
      'acc_login': 'Login',
      'acc_messages': 'Messages',
      'acc_favorite': 'Favorites',
      'acc_settings': 'Settings',
      'acc_aboutapp': 'About App',
      'acc_feedback': 'Feedback',
      'acc_contactus': 'Contact Us',
      'sett_fontsize': 'Font Size',
      'sett_fontstyle': 'Font Style',
      'sett_fontcolor': 'Font Color',
      'sett_defaultlang': 'Default Language',
      'sett_savesettings': 'Save Settings',
      'sett_choosecolor': 'Choose Color',
      'agpeya_first': '1st Hour',
      'agpeya_third': '3rd Hour',
      'agpeya_sixth': '6th Hour',
      'agpeya_nineth': '9th Hour',
      'agpeya_eleventh': '11th Hour',
      'agpeya_twelfth': '12th Hour',
      'agpeya_viel': 'Veil',
      'agpeya_midnight': 'Midnight',
      'agpeya_prayers': 'Prayers',
      'settings_saved_pop': 'Settings saved, please restart the App.',
      'reader_page_sections_header': 'Sections',
      'home_father_message': 'Message From Father',
      'home_read_bible': 'Read the Bible',
      'home_listen_to_sermon': 'Listen to Sermon',
      'home_readings': 'Readings',
      'home_agpeya': 'Agpeya',
      'home_todays_readings': 'Today\'s Readings',
      'sett_disp_lang1': 'Display Language 1',
      'sett_disp_lang2': 'Display Language 2',
    },
    'ar': {
      'app_name': 'China Coptic',
      'home_page': 'الرئيسية',
      'bible_page': 'الكتاب المقدس',
      'catalogue_page': 'الفهرس',
      'listen_page': 'استمع',
      'account_page': 'الحساب',
      'cat_agpeya': 'الأجبية',
      'cat_psalmody': 'الإبصلمودية',
      'cat_liturgies': 'القداسات',
      'cat_melodies': 'الألحان',
      'cat_clergy': 'الإكليروس',
      'cat_readings': 'القراءات',
      'cat_index': 'الفهرس',
      'cat_special': 'خاص',
      'read_vespers': 'عشية',
      'read_matins': 'باكر',
      'read_Liturgy': 'القداس',
      'read_antiphonary': 'الأنطيفناري',
      'acc_login': 'تسجيل الدخول',
      'acc_messages': 'الرسائل',
      'acc_favorite': 'المفضلة',
      'acc_settings': 'الإعدادات',
      'acc_aboutapp': 'عن التطبيق',
      'acc_feedback': 'ملاحظات',
      'acc_contactus': 'اتصل بنا',
      'sett_fontsize': 'حجم الخط',
      'sett_fontstyle': 'نمط الخط',
      'sett_fontcolor': 'لون الخط',
      'sett_defaultlang': 'اللغة الافتراضية',
      'sett_savesettings': 'حفظ الإعدادات',
      'sett_choosecolor': 'اختر اللون',
      'agpeya_first': 'الساعة الأولى',
      'agpeya_third': 'الساعة الثالثة',
      'agpeya_sixth': 'الساعة السادسة',
      'agpeya_nineth': 'الساعة التاسعة',
      'agpeya_eleventh': 'الساعة الحادية عشر',
      'agpeya_twelfth': 'الساعة الثانية عشر',
      'agpeya_viel': 'صلاة الحجاب',
      'agpeya_midnight': 'صلاة نصف الليل',
      'agpeya_prayers': 'صلوات',
      'settings_saved_pop': 'تم حفظ الإعدادات، يرجى إعادة تشغيل التطبيق',
      "reader_page_sections_header": "الأقسام",
      "home_father_message": "رسالة من الأب",
      "home_read_bible": "اقرأ الكتاب المقدس",
      "home_listen_to_sermon": "استمع إلى العظة",
      "home_readings": "القراءات",
      "home_agpeya": "الأجبية",
      "home_todays_readings": "قراءات اليوم",
      "sett_disp_lang1": "لغة العرض 1",
      "sett_disp_lang2": "لغة العرض 2",
    },
    'zh_hant': {
      'app_name': 'China Coptic',
      'home_page': '主頁',
      'bible_page': '聖經',
      'catalogue_page': '目錄',
      'listen_page': '聽',
      'account_page': '帳戶',
      'cat_agpeya': '時辰禱文',
      'cat_psalmody': '讚美詩',
      'cat_liturgies': '聖祭禮',
      'cat_melodies': '聖歌',
      'cat_clergy': '神職人員',
      'cat_readings': '讀經',
      'cat_index': '索引',
      'cat_special': '特別',
      'read_vespers': '晚禱',
      'read_matins': '晨禱',
      'read_Liturgy': '感恩祭',
      'read_antiphonary': '輪唱詩集',
      'acc_login': '登入',
      'acc_messages': '訊息',
      'acc_favorite': '收藏',
      'acc_settings': '設定',
      'acc_aboutapp': '關於應用',
      'acc_feedback': '反饋',
      'acc_contactus': '聯絡我們',
      'sett_fontsize': '字體大小',
      'sett_fontstyle': '字體樣式',
      'sett_fontcolor': '字體顏色',
      'sett_defaultlang': '預設語言',
      'sett_savesettings': '保存設定',
      'sett_choosecolor': '選擇顏色',
      'agpeya_first': '第一時辰',
      'agpeya_third': '第三時辰',
      'agpeya_sixth': '第六時辰',
      'agpeya_nineth': '第九時辰',
      'agpeya_eleventh': '第十一時辰',
      'agpeya_twelfth': '第十二時辰',
      'agpeya_viel': '面紗祈禱',
      'agpeya_midnight': '午夜祈禱',
      'agpeya_prayers': '禱告',
      'settings_saved_pop': '設定已儲存，請重新啟動應用程式。',
      "reader_page_sections_header": "章節",
      "home_father_message": "神父的訊息",
      "home_read_bible": "閱讀聖經",
      "home_listen_to_sermon": "聆聽講道",
      "home_readings": "經文閱讀",
      "home_agpeya": "阿格佩亞祈禱書",
      "home_todays_readings": "今日經文",
      "sett_disp_lang1": "顯示語言1",
      "sett_disp_lang2": "顯示語言2",
    },
    'zh_hans': {
      'app_name': 'China Coptic',
      'home_page': '主页',
      'bible_page': '圣经',
      'catalogue_page': '目录',
      'listen_page': '听',
      'account_page': '我的',
      'cat_agpeya': '时辰祷文',
      'cat_psalmody': '赞美诗',
      'cat_liturgies': '圣祭礼',
      'cat_melodies': '圣歌',
      'cat_clergy': '神职人员',
      'cat_readings': '读经',
      'cat_index': '索引',
      'cat_special': '特别',
      'read_vespers': '晚祷',
      'read_matins': '晨祷',
      'read_Liturgy': '感恩祭',
      'read_antiphonary': '轮唱诗集',
      'acc_login': '登录',
      'acc_messages': '消息',
      'acc_favorite': '收藏',
      'acc_settings': '设置',
      'acc_aboutapp': '关于应用',
      'acc_feedback': '反馈',
      'acc_contactus': '联系我们',
      'sett_fontsize': '字体大小',
      'sett_fontstyle': '字体样式',
      'sett_fontcolor': '字体颜色',
      'sett_defaultlang': '默认语言',
      'sett_savesettings': '保存设置',
      'sett_choosecolor': '选择颜色',
      'agpeya_first': '第一时辰',
      'agpeya_third': '第三时辰',
      'agpeya_sixth': '第六时辰',
      'agpeya_nineth': '第九时辰',
      'agpeya_eleventh': '第十一时辰',
      'agpeya_twelfth': '第十二时辰',
      'agpeya_viel': '面纱祈祷',
      'agpeya_midnight': '午夜祈祷',
      'agpeya_prayers': '祷告',
      'settings_saved_pop': '设置已保存，请重新启动应用程序。',
      "reader_page_sections_header": "章节",
      "home_father_message": "神父寄语",
      "home_read_bible": "阅读圣经",
      "home_listen_to_sermon": "听讲道",
      "home_readings": "经文阅读",
      "home_agpeya": "阿格佩亚祈祷书",
      "home_todays_readings": "今日经文",
      "sett_disp_lang1": "显示语言1",
      "sett_disp_lang2": "显示语言2",
    },
  };
}
